spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 694075181202-ldfjhdsk12av2nms7vjh4ftvn4c9s6fm.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile